export interface ReleaseNote {
  version: string;
  date: string;
  title: string;
  summary: string;
  changes: string[];
  githubUrl: string;
}

const REPOSITORY_URL = "https://github.com/ripper234/ChessRiot";

export const RELEASES: ReleaseNote[] = [
  {
    version: "0.14.0-capture.1",
    date: "2026-07-28",
    title: "Captures hit back",
    summary: "This isolated preview turns captures into short, physical attacks while authoritative chess state stays immediate and safe.",
    changes: [
      "Kept the victim visible until impact, then revealed the already-authoritative final position.",
      "Added a sword slash for pawns, leap attack for knights, and distinct bishop, rook, queen, and king actions.",
      "Sequenced multiple observed moves and both legs of Magic turns without delaying or changing server commits.",
      "Added an instant six-piece Capture Lab plus reduced-motion behavior for branch review.",
    ],
    githubUrl: `${REPOSITORY_URL}/tree/feature/capture-combat-animations`,
  },
  {
    version: "0.13.4",
    date: "2026-07-28",
    title: "Invitations, copied",
    summary: "Multiplayer invitations now copy straight to the clipboard instead of opening the operating system share sheet.",
    changes: [
      "Replaced the native share dialog with one direct Copy invitation link action.",
      "Confirmed successful copies in place and kept the private link selectable when clipboard access is unavailable.",
    ],
    githubUrl: `${REPOSITORY_URL}/tree/release/v0.13.4`,
  },
  {
    version: "0.13.3",
    date: "2026-07-28",
    title: "Riot Bot on the board",
    summary: "Solo replies now appear locally almost at once and both plies are saved together by one authoritative request.",
    changes: [
      "Ran the same deterministic Riot Bot search in the browser and on the server, preserving every level’s evaluation, depth, and node budget.",
      "Showed the human move first, then its predicted bot reply, while keeping the board locked until the server confirms the turn.",
      "Revalidated the bot reply server-side and atomically stored the human and bot plies in one database batch.",
      "Removed the second bot request and successful post-commit database reads while retaining pending-turn recovery for older or interrupted games.",
    ],
    githubUrl: `${REPOSITORY_URL}/tree/release/v0.13.3`,
  },
  {
    version: "0.13.2",
    date: "2026-07-28",
    title: "Riot Bot, right away",
    summary: "Riot Bot now answers promptly even when the hosted edge freezes its runtime clock during search.",
    changes: [
      "Added a deterministic node cap alongside the existing elapsed-time search budget.",
      "Kept every bot level’s depth, move ordering, evaluation, and tactical checkmate behavior unchanged.",
      "Added a frozen-clock regression that reproduces the hosted runtime and bounds Level 5 search.",
    ],
    githubUrl: `${REPOSITORY_URL}/tree/release/v0.13.2`,
  },
  {
    version: "0.13.1",
    date: "2026-07-28",
    title: "Community within reach",
    summary: "The ChessRiot WhatsApp community is now one tap away from both the public homepage and the in-game App panel.",
    changes: [
      "Added a clear WhatsApp community link to the public homepage.",
      "Added the same link to the App panel without interrupting the current game.",
      "Centralized the destination and opened both placements safely in a separate tab.",
    ],
    githubUrl: `${REPOSITORY_URL}/tree/release/v0.13.1`,
  },
  {
    version: "0.13.0",
    date: "2026-07-27",
    title: "Your turn, even when closed",
    summary: "A multiplayer seat can now opt one browser into a generic turn notification for one game, including after ChessRiot is closed.",
    changes: [
      "Added opt-in Web Push turn alerts to each multiplayer game’s App panel.",
      "Bound every browser subscription to one game and one authorized seat, so disabling one game leaves that device’s other game alerts intact.",
      "Delivered notifications only after a committed opponent move, with duplicate suppression, stale-endpoint cleanup, and no private seat key or player detail in the payload.",
      "Restricted push endpoints, validated notification navigation, and kept delivery best-effort so a push-service failure can never affect the chess move.",
    ],
    githubUrl: `${REPOSITORY_URL}/tree/release/v0.13.0`,
  },
  {
    version: "0.12.1",
    date: "2026-07-27",
    title: "Riot theme verified",
    summary: "The release checks now follow the new flat Riot default.",
    changes: [
      "Updated rendered-page regression coverage from the retired Blockfield label to Riot.",
    ],
    githubUrl: `${REPOSITORY_URL}/tree/release/v0.12.1`,
  },
  {
    version: "0.12.0",
    date: "2026-07-27",
    title: "Crisp 2D chess",
    summary: "The board and pieces now use one clean, modern 2D visual system instead of bevels, block shadows, and platform-dependent glyphs.",
    changes: [
      "Introduced six original flat vector silhouettes shared by live play, drag, promotion, captures, replay, recent games, and checkmate.",
      "Rebuilt board squares, frames, coordinates, move targets, captures, selection, and check states with solid color and clean rings.",
      "Made Riot the fresh teal-and-ivory default while preserving every existing theme as a palette choice.",
      "Replaced the tilted homepage mock board with a front-on 2D board using the same production pieces.",
    ],
    githubUrl: `${REPOSITORY_URL}/tree/release/v0.12.0`,
  },
  {
    version: "0.11.1",
    date: "2026-07-26",
    title: "One game, still moving",
    summary: "The 90-second demo now follows Ron and Omri through one asynchronous match, with the video filling the page instead of sitting below a large headline.",
    changes: [
      "Replaced the feature-list narration with a complete story from warm-up through invitation, reply, return, and replay.",
      "Made the video occupy roughly 90–94% of the viewport width and reduced the page heading to a compact label.",
      "Reordered the real interface captures around the story while removing inactive Magic Rules from the narration.",
      "Versioned the storyboard contract so an outdated Control build cannot publish stale video over the current story.",
    ],
    githubUrl: `${REPOSITORY_URL}/tree/release/v0.11.1`,
  },
  {
    version: "0.11.0",
    date: "2026-07-26",
    title: "ChessRiot in 90 seconds",
    summary: "A narrated, captioned walkthrough now shows Solo, themes, replay, and private multiplayer before you start a game.",
    changes: [
      "Added a public 90-second demo page linked directly from the homepage.",
      "Built the walkthrough from current Development interface captures with narration, subtitles, and audio.",
      "Separated video regeneration from application releases by publishing validated media through a versioned R2 manifest.",
      "Added a signed, owner-only, rate-limited regeneration lane for the ChessRiot Control panel.",
    ],
    githubUrl: `${REPOSITORY_URL}/tree/release/v0.11.0`,
  },
  {
    version: "0.10.2",
    date: "2026-07-26",
    title: "Cleaner foundations",
    summary: "Shared gameplay presentation and request logic is now easier to maintain without changing how ChessRiot plays.",
    changes: [
      "Centralized board orientation, piece labels, difficulty labels, outcome text, and live status text.",
      "Centralized new-game request payloads and authenticated client request helpers.",
      "Added focused regression tests while preserving the Magic Rules Coming Soon boundary.",
    ],
    githubUrl: `${REPOSITORY_URL}/tree/release/v0.10.2`,
  },
  {
    version: "0.10.1",
    date: "2026-07-26",
    title: "Magic safely paused",
    summary: "Magic Rules remain visible, but new rule entry is paused while the feature develops in isolation.",
    changes: [
      "Replaced new-game Magic rule entry with a clear Coming Soon placeholder.",
      "Removed the runtime LLM compiler, its endpoint, and its token-consuming path from the stable release.",
      "Moved active Magic development to an isolated feature branch and preview lane.",
    ],
    githubUrl: `${REPOSITORY_URL}/tree/release/v0.10.1`,
  },
  {
    version: "0.9.3",
    date: "2026-07-26",
    title: "Solo from the start",
    summary: "New games now open in Solo mode, while preserving White's first move in every game.",
    changes: [
      "Selected Solo by default on the new-game screen and showed the Level 3 Riot Bot control immediately.",
      "Kept Multiplayer one tap away without changing either mode's saved behavior.",
      "Added regression coverage for the default selection and the existing White-first invariant.",
    ],
    githubUrl: `${REPOSITORY_URL}/tree/release/v0.9.3`,
  },
  {
    version: "0.9.2",
    date: "2026-07-25",
    title: "First-move history fix",
    summary: "Back now works even while the first Magic move of a game is still being staged.",
    changes: [
      "Kept the Back arrow available at ply zero when a staged Magic position is visible.",
      "Made Back cancel that draft and reveal the authoritative starting position.",
    ],
    githubUrl: `${REPOSITORY_URL}/tree/release/v0.9.2`,
  },
  {
    version: "0.9.1",
    date: "2026-07-25",
    title: "History polish",
    summary: "History now follows the position you can actually see, with stronger mobile and keyboard behavior.",
    changes: [
      "Kept the immediately previous position available while a Solo move is shown optimistically.",
      "Made Back from a staged Magic first leg return to the latest authoritative position without skipping a ply.",
      "Removed historical board squares from keyboard navigation while keeping their position labels available.",
      "Moved history controls outside the live status announcement and enlarged their mobile touch targets.",
      "Restored focus safely after move confirmation, including promotion and committed-move flows.",
      "Clarified that Confirm every move is stored in the current browser.",
    ],
    githubUrl: `${REPOSITORY_URL}/tree/release/v0.9.1`,
  },
  {
    version: "0.9.0",
    date: "2026-07-25",
    title: "History at hand",
    summary: "Browse earlier positions directly on the board and optionally confirm every move before sending it.",
    changes: [
      "Added always-visible Back and Forward arrows that step through committed positions without changing the live game.",
      "Kept historical viewing pinned when a new move arrives, with a direct Go Live control and frame-specific check, captures, and last-move highlights.",
      "Added a browser-local Confirm every move setting that is off by default.",
      "Applied one confirmation to every human move path, including tap, drag, promotion, and complete atomic Magic turns.",
      "Blocked stale and duplicate confirmations before they can submit a move.",
    ],
    githubUrl: `${REPOSITORY_URL}/tree/release/v0.9.0`,
  },
  {
    version: "0.8.2",
    date: "2026-07-25",
    title: "One front door",
    summary: "ChessRiot now has one fixed public homepage and direct guest play with no login gate.",
    changes: [
      "Made the public homepage identical for every visitor, independent of hosting identity and saved game theme.",
      "Moved new-game setup to /app and enabled guest Solo and Multiplayer creation with a display name.",
      "Made private seat links authoritative for guest play while preserving existing account memberships and older games.",
      "Limited themes to active games so public, setup, invitation, changelog, loading, and error pages keep one consistent style.",
      "Removed all user-facing login prompts and kept the retired CAPTCHA path absent.",
    ],
    githubUrl: `${REPOSITORY_URL}/tree/release/v0.8.2`,
  },
  {
    version: "0.8.1",
    date: "2026-07-25",
    title: "Direct entry",
    summary: "Players now enter ChessRiot immediately, without a separate human-check screen.",
    changes: [
      "Removed the Turnstile screen, verification request, and CAPTCHA-bound application session.",
      "Kept trusted hosting identity, account-bound game membership, request-origin checks, and account rate limits.",
      "Retired the old CAPTCHA endpoint and redirected existing verification entry points safely into the game.",
    ],
    githubUrl: `${REPOSITORY_URL}/tree/release/v0.8.1`,
  },
  {
    version: "0.8.0",
    date: "2026-07-25",
    title: "Knights move twice",
    summary: "Magic knights can now move twice, and game requests work correctly inside the production sandbox.",
    changes: [
      "Made “Knights move twice.” a real deterministic Magic Rule for Solo and Multiplayer games.",
      "Generalized atomic two-leg turns so the same enabled rook or knight may move again, while a checking first leg still ends the turn.",
      "Kept existing v1 Magic Rule documents readable and unchanged while storing knight-enabled games in the compatible v2 schema.",
      "Extended tap, drag, keyboard, replay, move history, labels, and Riot Bot play to two-step knights.",
      "Fixed the production request-origin blocker without relaxing cross-site protection.",
    ],
    githubUrl: `${REPOSITORY_URL}/tree/release/v0.8.0`,
  },
  {
    version: "0.7.0",
    date: "2026-07-25",
    title: "Magic Rules",
    summary: "Every new Solo or Multiplayer game can optionally carry its own safe, immutable rule changes.",
    changes: [
      "Added an optional Magic Rules box to game creation with a concise natural-language prompt.",
      "Compiled recognized prompts into versioned rules and rejected unsupported text instead of executing arbitrary code or silently ignoring it.",
      "Added atomic two-step rook turns: the same rook may move again before the turn ends, while giving check ends the turn immediately.",
      "Added no-promotion, no-castling, and no-en-passant rules with server, client, replay, and Riot Bot enforcement.",
      "Showed Magic Rules before joining, during play, in replay and move history, and on My Games cards.",
    ],
    githubUrl: `${REPOSITORY_URL}/tree/release/v0.7.0`,
  },
  {
    version: "0.6.0",
    date: "2026-07-25",
    title: "Every game, every turn",
    summary: "A complete My Games history and account-aware alerts make asynchronous play reliable across devices.",
    changes: [
      "Added cursor pagination so My Games can reach the complete account history instead of stopping at 50 games.",
      "Added clear Your turn, Opponent's turn, Waiting, Won, Lost, and Draw states to every game card.",
      "Made open-app opponent-move alerts watch all owned multiplayer games through the account session.",
      "Removed the alert dependency on a legacy private-seat token or the currently open game route.",
      "Added a clear Switch Account action through the trusted ChatGPT sign-out flow.",
    ],
    githubUrl: `${REPOSITORY_URL}/tree/release/v0.6.0`,
  },
  {
    version: "0.5.0",
    date: "2026-07-24",
    title: "Secure accounts and a bigger board",
    summary: "Account access, a human check, a board-first layout, and original illustrated themes make ChessRiot safer and more immersive.",
    changes: [
      "Required a ChessRiot account and server-verified CAPTCHA before any game could be created or played.",
      "Added account-bound game access, per-account rate limits, and bot-turn leases to reduce automated abuse and duplicate AI work.",
      "Made the board fill the available desktop or mobile viewport and collapsed secondary match tools.",
      "Showed the starting position before animating Riot Bot’s White opening when the player starts as Black.",
      "Placed captured Black pieces with White and captured White pieces with Black.",
      "Added seven original illustrated theme backgrounds, including medieval army and moonlit castle styles, plus two new themes.",
    ],
    githubUrl: `${REPOSITORY_URL}/tree/release/v0.5.0`,
  },
  {
    version: "0.4.1",
    date: "2026-07-24",
    title: "Viewport clearance",
    summary: "Short desktop and landscape layouts keep the board, replay, and controls usable.",
    changes: [
      "Kept the complete game board above the utility dock across common desktop heights.",
      "Preserved usable game and replay board sizes in short landscape viewports with vertical scrolling.",
      "Added clearance after the final mobile card and compacted replay controls around the board.",
      "Removed a duplicate checkmate announcement and made invalid deadline text neutral.",
    ],
    githubUrl: `${REPOSITORY_URL}/tree/release/v0.4.1`,
  },
  {
    version: "0.4.0",
    date: "2026-07-24",
    title: "A more personal async game",
    summary: "Themes, replay, safe reactions, install support, and real move deadlines deepen every match.",
    changes: [
      "Added nine original themes for the app, board, pieces, panels, and background.",
      "Added an accessible visual picker that works from every route and synchronizes across tabs.",
      "Added six rate-limited, preset-only multiplayer reactions, a per-game hide control, and a 15-minute Good Game or Thanks courtesy window.",
      "Added a short theme-aware victory finisher with reduced-motion support.",
      "Added a read-only game replay with step controls and keyboard navigation.",
      "Added one, three, or five-day multiplayer move deadlines, defaulting to three days.",
      "Added installable PWA support, an unseen-release dot, and opt-in open-app opponent-move notifications.",
      "Made the exact release version visible on every route and state.",
    ],
    githubUrl: `${REPOSITORY_URL}/tree/release/v0.4.0`,
  },
  {
    version: "0.3.5",
    date: "2026-07-24",
    title: "Instant move polish",
    summary: "Immediate solo moves now keep their sound and complete observability trail.",
    changes: [
      "Restored one accepted move or capture sound for the human ply.",
      "Restored game-completion telemetry when Riot Bot delivers the final move.",
      "Kept race telemetry limited to the move that actually committed.",
    ],
    githubUrl: `${REPOSITORY_URL}/tree/release/v0.3.5`,
  },
  {
    version: "0.3.4",
    date: "2026-07-24",
    title: "Instant solo moves",
    summary: "Your piece now moves immediately while Riot Bot thinks in the background.",
    changes: [
      "Added a reversible local preview for every legal solo move before the server response arrives.",
      "Made the human move durable and visible before Riot Bot starts its reply.",
      "Added background bot-turn recovery so refresh or browser closure cannot strand a solo game.",
    ],
    githubUrl: `${REPOSITORY_URL}/tree/release/v0.3.4`,
  },
  {
    version: "0.3.3",
    date: "2026-07-24",
    title: "Unmistakable piece colors",
    summary: "White and Black now use the same solid voxel-piece shapes with clearly contrasting colors.",
    changes: [
      "Replaced hollow White glyphs with solid light pieces so the player color cannot look inverted.",
      "Reduced the bright outline on Black pieces so they read as Black at a glance.",
    ],
    githubUrl: `${REPOSITORY_URL}/tree/release/v0.3.3`,
  },
  {
    version: "0.3.2",
    date: "2026-07-24",
    title: "Laptop viewport polish",
    summary: "The complete board now stays inside a common laptop viewport at normal browser zoom.",
    changes: [
      "Tightened the desktop height cap after real-browser visual QA so the board no longer clips at the bottom.",
    ],
    githubUrl: `${REPOSITORY_URL}/tree/release/v0.3.2`,
  },
  {
    version: "0.3.1",
    date: "2026-07-24",
    title: "A clearer, complete game board",
    summary: "The board now fits shorter screens, makes player colors and check unmistakable, and adds captured pieces and game-ending controls.",
    changes: [
      "Made the full board fit common laptop screens at normal browser zoom and increased important label sizes.",
      "Added explicit White and Black player cards plus captured-piece trays.",
      "Highlighted the checked king and explained exactly when a move fails to answer check.",
      "Added New Game and confirmed End Game or Cancel Game actions.",
      "Renamed computer difficulty to bot level.",
    ],
    githubUrl: `${REPOSITORY_URL}/tree/release/v0.3.1`,
  },
  {
    version: "0.3.0",
    date: "2026-07-24",
    title: "A faster start and clearer releases",
    summary: "A much simpler home screen, visible board motion, in-app feedback, and a public version history.",
    changes: [
      "Simplified the new-game flow around name, mode, difficulty, and one primary action.",
      "Added short move and capture animations with reduced-motion support.",
      "Added a feedback form and an owner-only feedback pool.",
      "Added this changelog to every environment.",
    ],
    githubUrl: `${REPOSITORY_URL}/tree/release/v0.3.0`,
  },
  {
    version: "0.2.2",
    date: "2026-07-24",
    title: "Correct solo turns and observability",
    summary: "Riot Bot can now play either color correctly, chess draw rules are more precise, and operations are visible per environment.",
    changes: [
      "Riot Bot opens automatically when it is White.",
      "Added claimable and automatic FIDE draw handling.",
      "Added privacy-safe health, action, error, and latency telemetry.",
    ],
    githubUrl: `${REPOSITORY_URL}/tree/release/v0.2.2`,
  },
  {
    version: "0.2.1",
    date: "2026-07-24",
    title: "Version safety",
    summary: "Changed deployments can no longer silently reuse or decrease the app version.",
    changes: [
      "Added a single SemVer source and release commands.",
      "Added build-time checks for reused or inconsistent versions.",
    ],
    githubUrl: `${REPOSITORY_URL}/tree/release/v0.2.1`,
  },
  {
    version: "0.2.0",
    date: "2026-07-24",
    title: "Solo play and drag controls",
    summary: "Play Riot Bot at five difficulty levels, or drag pieces in multiplayer.",
    changes: [
      "Added persistent solo games against Riot Bot.",
      "Added five difficulty levels with Medium as the default.",
      "Added mouse and touch drag-and-drop while preserving tap and keyboard input.",
    ],
    githubUrl: `${REPOSITORY_URL}/tree/release/v0.2.0`,
  },
  {
    version: "0.1.2",
    date: "2026-07-24",
    title: "Portable private links",
    summary: "Private player links now work across computers and the game has a block-world visual identity.",
    changes: [
      "Embedded the private seat credential safely in the URL fragment.",
      "Added explicit private-link sharing and cross-device recovery.",
      "Restyled the complete experience with an original voxel-inspired look.",
    ],
    githubUrl: `${REPOSITORY_URL}/tree/release/v0.1.2`,
  },
  {
    version: "0.1.1",
    date: "2026-07-24",
    title: "Identity, sound, and resilience",
    summary: "The first polish release added ChessRiot’s visual identity, game sounds, and reliability fixes.",
    changes: [
      "Added move, capture, check, result, and invalid-action sounds.",
      "Added mute controls, clearer loading, and safer local storage.",
      "Improved invitation, status, and promotion interactions.",
    ],
    githubUrl: `${REPOSITORY_URL}/tree/release/v0.1.1`,
  },
  {
    version: "0.1.0",
    date: "2026-07-23",
    title: "Playable async chess",
    summary: "The first public prototype let two people create, join, resume, and finish a legal asynchronous chess game.",
    changes: [
      "Added one-use invitations and private player seats.",
      "Added complete standard chess rules and immutable move history.",
      "Added persistent two-device play with server-authoritative state.",
    ],
    githubUrl: `${REPOSITORY_URL}/tree/release/v0.1.0`,
  },
];

export const SOURCE_URL = REPOSITORY_URL;
