export interface ReleaseNote {
  version: string;
  date: string;
  title: string;
  summary: string;
  changes: string[];
  githubUrl: string;
}

const REPOSITORY_URL = "https://github.com/ripper234/ChessRiot";
const commitSource = (sha: string) => `${REPOSITORY_URL}/commit/${sha}`;

export const RELEASES: ReleaseNote[] = [
  {
    version: "0.30.1",
    date: "2026-09-21",
    title: "Security updates and clearer invitation checks",
    summary: "Update vulnerable dependencies, show saved openings before accepting, and improve notification-test recovery.",
    changes: [
      "Patch Next.js, image processing and ID-generator dependencies; require the security audit before release.",
      "Show whether White has already moved in incoming dashboard and activity invitations.",
      "Offer an immediate restart when a notification test loses earlier evidence, and clean up through the current service worker.",
      "Preserve mixed-language player names in status and recap text.",
    ],
    githubUrl: `${REPOSITORY_URL}/tree/release/v0.30.1`,
  },
  {
    version: "0.30.0",
    date: "2026-09-21",
    title: "Invite now, play whenever",
    summary: "Leave after inviting a friend, or save your opening move before they accept.",
    changes: [
      "Make it clear that invitations are saved and you do not need to be online together.",
      "Let White play one opening turn in a pending day-paced game; your friend gets the full move limit when they accept.",
      "Preserve the opening through acceptance, retries and concurrent actions, with notifications for the correct player's turn.",
    ],
    githubUrl: `${REPOSITORY_URL}/tree/release/v0.30.0`,
  },
  {
    version: "0.29.1",
    date: "2026-09-21",
    title: "Keep turn notifications until you act",
    summary: "Opening the browser or viewing your game no longer dismisses its current turn notification.",
    changes: [
      "Keep the reminder until you tap or dismiss it, or a newer game position makes it obsolete.",
      "Let you return manually during the four-round test and still tap the notification from Android’s notification drawer.",
    ],
    githubUrl: `${REPOSITORY_URL}/tree/release/v0.29.1`,
  },
  {
    version: "0.29.0",
    date: "2026-09-20",
    title: "Simpler notification test, English by default",
    summary: "Follow one clear step at a time while checking all four real notifications on your phone.",
    changes: [
      "Show one instruction and one primary action, with the complete test results and real game available on demand.",
      "Keep every delivery, tap, game-opening and user-confirmation check, with clear retry and restart paths.",
      "Use English throughout sign-in, games, menus, settings and notification diagnostics while preserving user-entered text.",
    ],
    githubUrl: `${REPOSITORY_URL}/tree/release/v0.29.0`,
  },
  {
    version: "0.28.0",
    date: "2026-09-20",
    title: "Four-turn Android test on one device",
    summary: "Test closed-app notifications through four real turns against Riot Bot on the phone you are holding.",
    changes: [
      "Start the guided test from Settings or the new-game page, with no second device or account.",
      "Riot Bot waits eight seconds before each real reply; the ordinary turn queue sends only to the device that started the test.",
      "Inspect server delivery, persistent device receipts, notification taps and exact-game opening separately, then confirm the Android notification you saw.",
    ],
    githubUrl: `${REPOSITORY_URL}/tree/release/v0.28.0`,
  },
  {
    version: "0.27.8",
    date: "2026-09-20",
    title: "Recover notification setup and unblock healthy devices",
    summary: "Notification recovery is visible, existing device consent survives lost local preferences, and failing endpoints no longer hold up other devices.",
    changes: [
      "Prioritized first delivery attempts and used durable retry and lease times to drain each notification lane within its request budget.",
      "Preserved an account-confirmed device registration when its local preference is missing, while respecting explicit disable and dismiss choices.",
      "Added an optional, in-flow setup recovery notice with visible errors and a Not now action; notification taps recover when Android retires a window.",
      "Verified mixed-device failures, future leases, retry recovery without additional requests, and four alternating opponent turns in the built Worker. Physical Android delivery and long-outage recovery remain separate verification requirements.",
    ],
    githubUrl: `${REPOSITORY_URL}/tree/release/v0.27.8`,
  },
  {
    version: "0.27.7",
    date: "2026-08-15",
    title: "Recover games and notifications without stale screens",
    summary: "Game entry now starts in native Hebrew, stalled reads always offer an exit, accepted games update immediately, and Android notification recovery stays visible.",
    changes: [
      "Rendered protected game, invitation, Activity, and Settings states in native Hebrew before first paint while preserving left-to-right board coordinates and notation.",
      "Bound response-body reads, added visible Retry and Home recovery, clarified player referral links, and made lost join-response retries safe for the same account.",
      "Queued the creator's first-turn push exactly once when a link or direct challenge is accepted, and removed stale waiting copy as soon as the authoritative game becomes active.",
      "Made one global Activity bell available on every signed-in route and surfaced an actionable Android notification-block banner with safe Settings guidance and an explicit status recheck.",
    ],
    githubUrl: `${REPOSITORY_URL}/tree/release/v0.27.7`,
  },
  {
    version: "0.27.6",
    date: "2026-08-15",
    title: "Make multiplayer deadlines authoritative",
    summary: "One-, three-, and five-day games now enforce the same exact deadline across every action, account view, invitation, and notification path.",
    changes: [
      "Guarded moves, draw claims, resignations, and reactions with SQLite statement time, persisted delayed timeouts at their exact deadline, and suppressed expired turn pushes.",
      "Settled overdue games before Home, History, and Activity reads, while preserving legacy no-deadline games and consistent results for both seats.",
      "Required signed invite previews, disclosed pace before link or direct acceptance, removed stale cross-account seat redirects, preserved new invite links without local storage, and restricted waiting-challenge cancellation to its creator.",
      "Expanded built-worker coverage across every 1/3/5-day create, join, move, reset, rejection, timeout, result, reaction, notification, and Play Again path.",
    ],
    githubUrl: `${REPOSITORY_URL}/tree/release/v0.27.6`,
  },
  {
    version: "0.27.5",
    date: "2026-08-11",
    title: "Repair the notification lifecycle",
    summary: "Opted-in devices now repair missing subscriptions, preserve newer turn alerts, and drain durable delivery work without coupling lanes or over-leasing slow backlogs.",
    changes: [
      "Recreated missing or rotated browser subscriptions after granted consent, and required a focused authoritative game before clearing its turn alert.",
      "Serialized game-version-aware re-alerting and clearing so overlapping same-game pushes retain the newest turn while an exact provider retry stays deduplicated.",
      "Bound every delivery batch to one target per lane, isolated lane failures, terminalized exhausted rows, and made stale disablement and cap eviction preserve audit records until the 30-day sweep.",
    ],
    githubUrl: `${REPOSITORY_URL}/tree/release/v0.27.5`,
  },
  {
    version: "0.27.4",
    date: "2026-08-10",
    title: "Retry short push outages within the request",
    summary: "Opponent-turn and friend-request pushes now get a bounded third attempt without relying on an unsupported Sites background trigger.",
    changes: [
      "Retried failed notification lanes at about 0, 2, and 17 seconds while reserving time inside the Worker's post-response execution limit.",
      "Prioritized due failures over fresh pending rows, capped the final round to one row per failed lane, and preserved durable leases and superseded-turn checks.",
      "Added policy and end-to-end coverage for two provider failures followed by acceptance, and documented that later recovery still needs API traffic on Sites.",
    ],
    githubUrl: `${REPOSITORY_URL}/tree/release/v0.27.4`,
  },
  {
    version: "0.27.3",
    date: "2026-08-10",
    title: "Prepare scheduled notification retries",
    summary: "The release packaged a scheduled retry trigger, but live Sites validation did not produce the recurring event required for autonomous recovery.",
    changes: [
      "Added an every-minute Cron declaration while preserving immediate delivery and the short first retry.",
      "Verified that the declaration survived the build, then found no scheduled invocation in Development after the provider propagation window.",
      "Kept the scheduled handler for a future compatible host and moved current Sites reliability to the bounded request-time policy in v0.27.4.",
    ],
    githubUrl: `${REPOSITORY_URL}/tree/release/v0.27.3`,
  },
  {
    version: "0.27.2",
    date: "2026-08-08",
    title: "Prioritize Control notifications on mobile",
    summary: "Control-triggered player messages now use the same immediate delivery class and request the same persistent presentation as ChessRiot’s working Android device test.",
    changes: [
      "Changed exact-player Control messages from deferrable normal Web Push urgency to high urgency, matching turn alerts, friend requests, and the exact-device test.",
      "Unified diagnostic and ordinary service-message presentation so a passing device test no longer exercises a more visible notification branch than Control.",
      "Derived every service-message tag from the signed one-time grant nonce and added regressions for urgency, topic safety, and persistent service display.",
    ],
    githubUrl: `${REPOSITORY_URL}/tree/release/v0.27.2`,
  },
  {
    version: "0.27.1",
    date: "2026-08-07",
    title: "Diagnose notification delivery",
    summary: "The device test now distinguishes browser registration, push-service acceptance, service-worker receipt, notification creation, and operating-system presentation instead of claiming an unseen alert was displayed.",
    changes: [
      "Made the local test persistent with a unique tag and verified that the active service-worker registration retained it before advancing to the server test.",
      "Added a version handshake plus an exact one-time marker to the encrypted server push, then reported browser receipt, notification API resolution, and retained-notification stages to the same-origin Settings page without exposing an endpoint or payload.",
      "Replaced the false two-tests-sent success message with stage-specific results, desktop Windows banner and Do Not Disturb recovery, and Brave’s official independent notification test.",
    ],
    githubUrl: `${REPOSITORY_URL}/tree/release/v0.27.1`,
  },
  {
    version: "0.27.0",
    date: "2026-08-06",
    title: "Make notifications reach the device",
    summary: "Notification setup is now one explicit browser-to-server transaction, friend requests can alert closed devices, and challenging a friend is a primary action.",
    changes: [
      "Moved PushManager subscription and device registration into the Enable action, removed game-snapshot cancellation from notification setup, adopted late browser subscriptions safely, and made Not now revoke any late result.",
      "Added an exact-device test that separates local system display from server Web Push delivery, with fixed payloads, account ownership checks, and provider-stage outcomes.",
      "Queued friend-request alerts atomically with the request, retried transient delivery failures, suppressed rapid cancel-and-resend notification spam, and deep-linked notification taps to the actionable Activity inbox.",
      "Promoted Challenge a friend to the signed-in Home primary action, kept Riot Bot explicit, clarified the opponent and waiting-for-acceptance flow, and made the four Home actions responsive on tablet and mobile widths.",
    ],
    githubUrl: `${REPOSITORY_URL}/tree/release/v0.27.0`,
  },
  {
    version: "0.26.3",
    date: "2026-08-06",
    title: "Make Android notification recovery honest",
    summary: "Notification setup now identifies the failing browser or server stage, stays off the board, and safely resumes an interrupted Android Allow result.",
    changes: [
      "Separated service-worker, subscription, serialization, server-status, and device-registration failures into privacy-safe diagnostics, showing Brave Google Push Messaging guidance only when browser subscription creation fails.",
      "Moved setup errors entirely into Settings with a recovery bell, resumed a granted-but-interrupted onboarding decision after reload, and prevented a stale onboarding card from overwriting a concurrent Settings choice.",
      "Made service-worker precaching fail soft so one unavailable optional icon or manifest cannot abort background notification installation.",
    ],
    githubUrl: `${REPOSITORY_URL}/tree/release/v0.26.3`,
  },
  {
    version: "0.26.2",
    date: "2026-08-06",
    title: "Keep notifications optional",
    summary: "The one-time notification ask can always be skipped, and a browser or push-setup failure can never block play or loop after reload.",
    changes: [
      "Restored a clear Not now choice while keeping Enable notifications as the one user gesture that opens the browser permission request.",
      "Recorded the ask once per retained site and browser profile, independent of username, so skipping, switching accounts, or reloading cannot repeat it automatically.",
      "Made every post-permission setup failure terminal for onboarding, moved interrupted setup repair into the non-blocking app lifecycle, added browser-versus-server diagnostics, and kept deliberate recovery in Settings without re-entering the account gate.",
    ],
    githubUrl: `${REPOSITORY_URL}/tree/release/v0.26.2`,
  },
  {
    version: "0.26.1",
    date: "2026-08-06",
    title: "Ask the browser once",
    summary: "ChessRiot now makes one real notification-permission attempt per retained browser/device profile instead of repeating a username-level soft opt-in.",
    changes: [
      "Added one shared notification step for new and existing signed-in players, whose single Continue action opens the real browser permission request before play.",
      "Stored the attempt at the website and browser/device level before calling the permission API and serialized simultaneous tabs, so dismissal, denial, failure, reloads, and account changes cannot trigger automatic repeats.",
      "Made granted-but-interrupted setup resume subscription and server registration without another native prompt, while keeping Settings as a deliberate manual recovery path.",
    ],
    githubUrl: `${REPOSITORY_URL}/tree/release/v0.26.1`,
  },
  {
    version: "0.26.0",
    date: "2026-08-04",
    title: "Make notifications one clear choice",
    summary: "Mobile players can enable ChessRiot notifications once per device, and Control can safely test one exact player without a broadcast path.",
    changes: [
      "Added a dedicated mobile notification step after username onboarding and one inline offer for existing signed-in players, with Enable and Not now choices that never cover a game board or trigger permission without a click.",
      "Moved notification consent to an account-level device registry, so one opt-in covers existing and future multiplayer games while legacy per-game consent stays narrow until explicit re-consent.",
      "Made Settings the permanent global device control, detached subscriptions across sign-out and account changes, repaired rotated browser endpoints, prevented duplicate turn alerts during migration, and retained bounded stale-endpoint and transient-failure handling.",
      "Added owner-only Control inspection and single-player service/test sends with Unicode usernames, fixed title and destination, Production confirmation, single-execution signed grants with safe result replay, budgets, privacy-safe logs, and push-service-only result wording.",
    ],
    githubUrl: `${REPOSITORY_URL}/tree/release/v0.26.0`,
  },
  {
    version: "0.25.4",
    date: "2026-08-04",
    title: "Keep alerts off the board",
    summary: "Turn-alert setup no longer blocks mobile play, and Magic failures identify whether Production rejected the key or denied compiler access.",
    changes: [
      "Replaced the full-screen mobile turn-alert reminder with a one-time bell badge on Settings while keeping the per-game opt-in available inside Current game.",
      "Remembered the alert offer per game, matching the existing per-game subscription scope without repeatedly covering play.",
      "Separated rejected OpenAI credentials from project-permission failures in safe operational error codes and clarified that Magic checks support before creating a World.",
    ],
    githubUrl: `${REPOSITORY_URL}/tree/release/v0.25.4`,
  },
  {
    version: "0.25.3",
    date: "2026-08-04",
    title: "Keep cold releases observable",
    summary: "A new deployment now establishes its continuity baseline during the first root load, while health remains read-only and real storage changes still fail closed.",
    changes: [
      "Initialized the environment's storage epoch and account-identity mirror from the first root request after migrations, before Control can mistake an untouched release for a broken version.",
      "Kept the public health route strictly read-only and preserved hard failure when D1, object storage, environment identity, or account identity no longer matches.",
      "Added an end-to-end cold-release proof that root initialization creates the mirrored baseline and a later D1 binding swap is rejected.",
    ],
    githubUrl: `${REPOSITORY_URL}/tree/release/v0.25.3`,
  },
  {
    version: "0.25.2",
    date: "2026-08-04",
    title: "Make failure states recoverable",
    summary: "Magic errors now explain what failed without enabling free token spend, opponent-turn alerts survive transient failures, and deployments guard account access continuity.",
    changes: [
      "Committed each opponent-turn alert atomically with its move and added leased, bounded retries for network timeouts, rate limits, and temporary push-service failures.",
      "Revalidated the exact game version before delayed delivery, used an opaque push topic, cleaned expired endpoints, and stopped global provider incidents from disabling healthy devices.",
      "Kept Android alerts visible until an authoritative matching game snapshot opens, then cleared them, and made notification taps deterministic with a safe new-window fallback.",
      "Made compiled Magic rules a staging state and finalized the canonical World, compilation cache, source, and paid entitlement together before Apply Magic can succeed.",
      "Classified rule, connection, timeout, provider, and configuration failures; capped output; cached semantic rejections; and added account/global compile budgets plus a shared failure circuit.",
      "Mirrored the permanent D1 storage epoch outside D1, made health read-only, guarded account-identity continuity, and preserved approved Magic flags through the full upgrade chain.",
      "Repaired the interactive knight tutorial and made multiplayer challenges, invitation sharing, acceptance, and the waiting state one clear start-game flow.",
    ],
    githubUrl: `${REPOSITORY_URL}/tree/release/v0.25.2`,
  },
  {
    version: "0.25.1",
    date: "2026-08-04",
    title: "Make async turns calmer",
    summary: "Day-based games now focus on one visible move deadline, Quick Reactions are gone, and Android turn alerts can work after one per-game opt-in.",
    changes: [
      "Removed the Quick Reactions tab, panel, polling, bubbles, and client handlers from active and completed games.",
      "Removed cumulative live chess clocks from one-, three-, and five-day games while keeping the authoritative move deadline visible on mobile and desktop.",
      "Added a direct in-game Android turn-alert opt-in, complete VAPID configuration validation, and Brave-specific recovery guidance while keeping permission explicit and per game.",
    ],
    githubUrl: `${REPOSITORY_URL}/tree/release/v0.25.1`,
  },
  {
    version: "0.25.0",
    date: "2026-08-03",
    title: "Choose your own alphabet",
    summary: "Permanent usernames now work in Hebrew and other writing systems, with a normal Android keyboard and clear validation feedback.",
    changes: [
      "Accepted Unicode letters, marks, and numbers in 3–20-character permanent usernames while retaining internal dot, hyphen, and underscore separators.",
      "Unified normalized caseless identity across username claims, lookup, challenges, Magic access, and deleted-name reservation while keeping destructive confirmation display-exact.",
      "Removed Android credential autofill and automatic display-name prefilling from the permanent-handle field, using a normal directional text keyboard instead.",
      "Made invalid, reserved, taken, and unavailable username errors visible in one announced inline location without trapping the player behind disabled controls.",
      "Promoted the same tested source tree to Development and Production while preserving isolated data, OAuth credentials, secrets, and access policies.",
    ],
    githubUrl: `${REPOSITORY_URL}/tree/release/v0.25.0`,
  },
  {
    version: "0.24.0",
    date: "2026-08-03",
    title: "Create a chess multiverse",
    summary: "Magic Rules now compile explicitly into immutable, forkable Worlds with canonical wallet-style codes, a simple credit economy, and a connected popularity map.",
    changes: [
      "Added Apply Magic as the only paid compilation boundary, with an empty prompt, an example placeholder, durable global reuse, and one exact game entitlement per credit.",
      "Added canonical World identity so equivalent rules, phrases, ordering, and languages resolve to the same 160-bit displayable hash while the full digest guards collisions.",
      "Added creator attribution, parent-to-fork connections, World pages, and an accessible map whose node size follows games with a human move.",
      "Started every account with 10 credits, changed referral rewards from 100 to 10, and awarded World creators 1 credit after every 5 paid games in which the paying account makes a legal move.",
      "Made paid Apply requests safe under concurrency, interruption, and replay, and kept creator exports aggregate-only so popularity never reveals another player’s private game metadata.",
      "Moved active-game World rules out of the board column and into the desktop sidebar or the mobile World drawer.",
      "Extended Google-established ChessRiot sessions to a sliding one-year window while preserving immutable recent-authentication time for destructive account actions.",
    ],
    githubUrl: `${REPOSITORY_URL}/tree/release/v0.24.0`,
  },
  {
    version: "0.23.1",
    date: "2026-08-03",
    title: "Make launch signals fast",
    summary: "Control analytics now reaches Development reliably by replacing cold request-time schema work and scattered queries with one indexed aggregate read.",
    changes: [
      "Changed the owner-only analytics endpoint from request-time schema initialization plus ten independent database calls to one migration-backed D1 batch.",
      "Removed three unused daily-series queries and added time-filter indexes for accounts, games, moves, friend requests, referrals, and actor activity.",
      "Preserved the privacy-safe aggregate contract and mature signup-to-first-move journey without exposing player identifiers.",
    ],
    githubUrl: `${REPOSITORY_URL}/tree/release/v0.23.1`,
  },
  {
    version: "0.23.0",
    date: "2026-08-03",
    title: "Replay the finish",
    summary: "Completed matches can now become revocable public replays, while optional onboarding, safe recovery, and a leaner accessibility path prepare Development for launch testing.",
    changes: [
      "Made the 45-second tutorial fully opt-in from Settings, with no automatic first-account modal, stronger focus movement, live step announcements, and immediate reduced-motion transitions.",
      "Removed every public link to the current 90-second demo and excluded it from indexing while preserving the direct QA route and bounded owner-only regeneration workshop for a future replacement.",
      "Added bounded, coalesced recovery for account, signed-home, and initial game reads, including timeout, online, focus, visible-tab, and expired-session handling without ever retrying a game mutation automatically.",
      "Added opaque, participant-created public recap links for completed games with a read-only board, move replay, result details, native sharing, explicit revocation, and automatic revocation during account deletion.",
      "Kept recap pages free of seat keys, invitations, account identifiers, and mutation access, and made them noindex with a fresh opaque URL after revocation.",
      "Added keyboard skip navigation, stronger focus and forced-colors behavior, coarse-pointer target sizing, whole-second hidden-tab-aware clocks, and lower-cost visuals for Save-Data and very slow links.",
      "Added a privacy-safe mature-cohort signup-to-first-move aggregate for separate Development and Production monitoring without player identifiers or cross-environment joins.",
      "Updated the demo story recipe for future regeneration to describe optional onboarding and shareable recaps while leaving the current bundled video archived and unadvertised.",
    ],
    githubUrl: `${REPOSITORY_URL}/tree/release/v0.23.0`,
  },
  {
    version: "0.22.0",
    date: "2026-08-03",
    title: "Ask for the key",
    summary: "Locked early-access features now offer a clear invitation request, while Control gives the owner an exact queue for individual admission.",
    changes: [
      "Added a one-click Magic Rules invitation request with a durable Requested state and no false promise of immediate access.",
      "Added an exact red-badged Control queue that keeps Development and Production separate and supports one-account approval or dismissal.",
      "Made approval atomic with the existing server feature flag, reject replay and arbitrary feature or username input, and keep pending players blocked from Magic creation.",
      "Included pending requests in privacy export, removed them with account deletion, and kept access-request telemetry typed and identifier-free.",
      "Kept local and embedded previews usable by generating client telemetry identifiers with the existing secure browser-compatible UUID helper.",
    ],
    githubUrl: `${REPOSITORY_URL}/tree/release/v0.22.0`,
  },
  {
    version: "0.21.1",
    date: "2026-08-03",
    title: "Keep every promise",
    summary: "The launch-readiness release now closes tutorial, export, and retention edge cases before wider rollout.",
    changes: [
      "Made Escape use the same durable Skip path as the tutorial button, so a failed save leaves the tutorial open with a retry message instead of stranding the account.",
      "Changed account export to keyset-paginate complete game and move history and added an explicit completeness summary instead of silently stopping at fixed row caps.",
      "Applied telemetry and moderation-archive retention on every API request, with expired records excluded at their cutoff and physically removed on the next service request.",
    ],
    githubUrl: `${REPOSITORY_URL}/tree/release/v0.21.1`,
  },
  {
    version: "0.21.0",
    date: "2026-08-03",
    title: "Know what needs your move",
    summary: "A fast tutorial, one Activity inbox, player safety, privacy controls, launch analytics, and a truthful new demo prepare ChessRiot for 1.0.",
    changes: [
      "Added a skippable account-backed 45-second tutorial with interactive legal-move practice, Activity preview, durable completion, and Settings replay.",
      "Added one unread Activity inbox for friend requests, challenges, turns, and results, with inline responses and block-aware durable read state.",
      "Added outgoing-request cancellation, friend removal, bidirectional blocking, unblock management, private category-based safety reports, and an owner-only moderation queue.",
      "Added a Privacy & Data center for readable export, blocked-player management, and recently reauthenticated permanent deletion with username reservation and anonymization.",
      "Added a privacy-safe aggregate analytics API and a separate Control Analytics center with environment and time-window isolation plus honest unavailable states.",
      "Rebuilt the 90-second signed-out explainer around required accounts, permanent usernames, onboarding, Activity, friends, one-screen play, History, and data controls, with native captions and a final sign-in action.",
      "Moved Google Analytics 4, Hotjar, and any deeper 90-second interactive lesson to an explicit high-priority backlog instead of shipping third-party tracking by default.",
    ],
    githubUrl: `${REPOSITORY_URL}/tree/release/v0.21.0`,
  },
  {
    version: "0.20.0",
    date: "2026-08-03",
    title: "Bring your next rival",
    summary: "Personal player invites now turn a shared link into an instant connection, a ready challenge, and a protected new-player credit reward.",
    changes: [
      "Added one stable personal invite link per player with native sharing, clipboard fallback, and an invite landing page centered on the inviter.",
      "Connected players as friends automatically so either player can immediately configure and send a challenge.",
      "Awarded 100 credits only when a genuinely new Google account joins through the link and completes its permanent username.",
      "Protected rewards with first-touch attribution, one reward per new account, self-referral rejection, atomic credit and friendship writes, and privacy-safe route logging.",
      "Made selected History filters legible by removing the inherited duplicate-shadow effect while preserving their selected-state contrast.",
    ],
    githubUrl: `${REPOSITORY_URL}/tree/release/v0.20.0`,
  },
  {
    version: "0.19.1",
    date: "2026-08-03",
    title: "Your chess circle, all in one place",
    summary: "Required accounts, permanent usernames, friends, richer skins, and a focused game screen make ChessRiot feel complete across devices.",
    changes: [
      "Required Google sign-in for play and added one-time, globally unique username onboarding with clear character, safety, and permanence rules.",
      "Added a signed-in dashboard, automatic complete game history, username-based friend requests, and direct configured challenges with explicit accept or decline controls.",
      "Kept Magic Rules Coming Soon for most players while adding an owner-controlled, server-enforced account whitelist for supported experimental rules.",
      "Added cumulative player clocks and tightened the active-game layout so the board, status, and primary controls fit one common desktop or laptop screen.",
      "Added Mythic Beasts as the twelfth whole-app skin and gave every skin a richer, more distinctive procedural score and themed sound profile.",
      "Split sound-effect and music volume, added icons to Settings sections, and made every on/off preference a clear checkbox.",
      "Improved legal-target visibility, homepage piece alignment, capture and promotion motion, and the reduced-motion-safe postgame presentation.",
      "Separated the signed-out homepage from the account dashboard, moved legal links into registration, and aligned Development and Production on one tested source release.",
    ],
    githubUrl: `${REPOSITORY_URL}/tree/release/v0.19.1`,
  },
  {
    version: "0.18.1",
    date: "2026-08-02",
    title: "Private links stay decisive",
    summary: "The final Google-login audit keeps exact seat links authoritative and legacy Development history visible.",
    changes: [
      "Made an exact private-seat token select that seat even when the browser also carries a different account membership.",
      "Made guest-to-account linking and concurrent game retries settle safely without silently changing ownership.",
      "Preserved recent-game discovery for protected Development users who still have legacy Sites-only memberships.",
    ],
    githubUrl: `${REPOSITORY_URL}/tree/release/v0.18.1`,
  },
  {
    version: "0.18.0",
    date: "2026-08-02",
    title: "Your games, one account",
    summary: "Optional Google login lets new and explicitly linked games follow you across devices.",
    changes: [
      "Added environment-isolated Google OpenID Connect with exact callbacks, PKCE, signed state and sessions, and no stored provider tokens or email addresses.",
      "Kept guest creation, invitations, and exact private seat links fully usable when Google sign-in is absent or unavailable.",
      "Allowed a signed-in player to add only the exact legacy private seat they explicitly present, while keeping ordinary game reads ownership-neutral.",
      "Published current identity-independent Privacy and Terms routes from the same source in both environments and linked them from the public shell and Settings.",
      "Isolated the Development and Production OpenAI keys and added one fixed-marker, opt-in live LLM smoke test with no default CI spend.",
      "Implemented exact Development and Production OAuth callback routes while keeping Development protected by its Sites user allowlist.",
    ],
    githubUrl: `${REPOSITORY_URL}/tree/release/v0.18.0`,
  },
  {
    version: "0.17.0",
    date: "2026-08-01",
    title: "One world, one menu",
    summary: "Skins now shape the whole experience, while one Settings menu gathers audio, assistance, feedback, and game actions.",
    changes: [
      "Applied all 11 skins before paint across the homepage, setup, menus, board, pieces, music, and special effects.",
      "Unified duplicate controls into one accessible Settings menu with independent sound, music, master-volume, coach, celebration, notification, surrender, privacy, and version controls.",
      "Added low-key skin-specific music, longer piece-specific captures, special check, castling, queen-loss, promotion, and white-flag resignation effects.",
      "Replaced the separate replay dialog with a compact current-move row and expandable full move table, plus a complete captured-piece panel.",
      "Added a default-on local risk coach for obvious material losses and small tactical fork celebrations, each independently optional.",
      "Hardened bounded request parsing, health readiness, observability privacy, response headers, Magic compatibility, dependencies, CI, and release artifact validation.",
    ],
    githubUrl: `${REPOSITORY_URL}/tree/release/v0.17.0`,
  },
  {
    version: "0.16.0",
    date: "2026-08-01",
    title: "Every piece fights different",
    summary: "Captures now become short piece-specific combat, while missing required fields explain exactly what needs attention.",
    changes: [
      "Added distinct pawn, knight, bishop, rook, queen, and king capture actions with a visible victim reaction and impact.",
      "Kept combat pointer-transparent and non-blocking on top of the immediate optimistic board for both human and Riot Bot moves.",
      "Reconstructed en passant, capture promotion, and atomic two-leg effects from immutable move history without replaying them on refresh or history views.",
      "Added red inline errors, accessible descriptions, and first-invalid-field focus to Create Game, Join Game, and Feedback.",
      "Published /capture-lab as the visual regression surface for all six combat actions and reduced motion.",
    ],
    githubUrl: commitSource("3e81a0d535a4922ba966b5330470093cddaa1e53"),
  },
  {
    version: "0.15.0",
    date: "2026-07-30",
    title: "Instant moves and classic finishes",
    summary: "Moves now feel immediate in every game, and a new Mating Set teaches three essential endings.",
    changes: [
      "Painted locally legal Multiplayer moves immediately while preserving server-authoritative validation, rollback, and stale-write protection.",
      "Added Solo practice for King + Pawn, King + Rook, and King + Two Bishops against Riot Bot's lone king.",
      "Kept one version link in the active-game header so the duplicate global label cannot overlap the board.",
      "Retired Staging from the active deployment and owner-feedback model, leaving Development and Production.",
    ],
    githubUrl: commitSource("c3aec0d7087be86b80220ec4e7979f287aee4971"),
  },
  {
    version: "0.14.0",
    date: "2026-07-29",
    title: "Three new ways to riot",
    summary: "A new game menu launches three smaller chess setups in both Solo and Multiplayer.",
    changes: [
      "Added Pawn Riot, Half Army, and Pawn Duel while keeping Classic Chess selected by default.",
      "Made every setup server-owned, immutable, and compatible with Riot Bot, invitations, history, replay, and deadlines.",
      "Disclosed the selected game before joining and throughout the active match without accepting arbitrary starting positions.",
    ],
    githubUrl: commitSource("df5c9c1f394d9573f2339e6fb40a67b769e22276"),
  },
  {
    version: "0.13.5",
    date: "2026-07-28",
    title: "Feedback, accounted for",
    summary: "The owner control panel can count unresolved feedback exactly and safely mark individual items done.",
    changes: [
      "Added exact new, reviewed, closed, and unresolved feedback counts independent of the bounded item list.",
      "Added a separate short-lived feedback-management grant and an idempotent close action.",
      "Recorded privacy-safe feedback completion events with normalized routes and no feedback content.",
    ],
    githubUrl: commitSource("6d8e026fed3dcfedf707ad96edf52273a797ee0c"),
  },
  {
    version: "0.13.4",
    date: "2026-07-28",
    title: "Invitations, copied",
    summary: "Multiplayer invitations now copy straight to the clipboard instead of opening the operating system share sheet.",
    changes: [
      "Replaced the native share dialog with one direct Copy invitation link action.",
      "Confirmed successful copies in place and kept the private link selectable when clipboard access is unavailable.",
    ],
    githubUrl: commitSource("1f77d2fa99302f99853e7d0357f0ca9527f53a78"),
  },
  {
    version: "0.13.3",
    date: "2026-07-28",
    title: "Riot Bot on the board",
    summary: "Solo replies now appear locally almost at once and both plies are saved together by one authoritative request.",
    changes: [
      "Ran the same deterministic Riot Bot search in the browser and on the server, preserving every level’s evaluation, depth, and node budget.",
      "Showed the human move first, then its predicted bot reply, while keeping the board locked until the server confirms the turn.",
      "Revalidated the bot reply server-side and atomically stored the human and bot plies in one database batch.",
      "Removed the second bot request and successful post-commit database reads while retaining pending-turn recovery for older or interrupted games.",
    ],
    githubUrl: commitSource("e8f16b78e0f042b9829e2148b26da258cdc8d99b"),
  },
  {
    version: "0.13.2",
    date: "2026-07-28",
    title: "Riot Bot, right away",
    summary: "Riot Bot now answers promptly even when the hosted edge freezes its runtime clock during search.",
    changes: [
      "Added a deterministic node cap alongside the existing elapsed-time search budget.",
      "Kept every bot level’s depth, move ordering, evaluation, and tactical checkmate behavior unchanged.",
      "Added a frozen-clock regression that reproduces the hosted runtime and bounds Level 5 search.",
    ],
    githubUrl: commitSource("79bb9400af60617f74a71e8d667b93bed3022fdb"),
  },
  {
    version: "0.13.1",
    date: "2026-07-28",
    title: "Community within reach",
    summary: "The ChessRiot WhatsApp community is now one tap away from both the public homepage and the in-game App panel.",
    changes: [
      "Added a clear WhatsApp community link to the public homepage.",
      "Added the same link to the App panel without interrupting the current game.",
      "Centralized the destination and opened both placements safely in a separate tab.",
    ],
    githubUrl: commitSource("e0a44175cca99cbcf62e5759810ebe949dfa6938"),
  },
  {
    version: "0.13.0",
    date: "2026-07-27",
    title: "Your turn, even when closed",
    summary: "A multiplayer seat can now opt one browser into a generic turn notification for one game, including after ChessRiot is closed.",
    changes: [
      "Added opt-in Web Push turn alerts to each multiplayer game’s App panel.",
      "Bound every browser subscription to one game and one authorized seat, so disabling one game leaves that device’s other game alerts intact.",
      "Delivered notifications only after a committed opponent move, with duplicate suppression, stale-endpoint cleanup, and no private seat key or player detail in the payload.",
      "Restricted push endpoints, validated notification navigation, and kept delivery best-effort so a push-service failure can never affect the chess move.",
    ],
    githubUrl: commitSource("19dc71cd2035e890be23d50b8d77a0351ba1a4ad"),
  },
  {
    version: "0.12.1",
    date: "2026-07-27",
    title: "Riot theme verified",
    summary: "The release checks now follow the new flat Riot default.",
    changes: [
      "Updated rendered-page regression coverage from the retired Blockfield label to Riot.",
    ],
    githubUrl: commitSource("5269d23b7124fb9203c8916a28d38f92721aff0b"),
  },
  {
    version: "0.12.0",
    date: "2026-07-27",
    title: "Crisp 2D chess",
    summary: "The board and pieces now use one clean, modern 2D visual system instead of bevels, block shadows, and platform-dependent glyphs.",
    changes: [
      "Introduced six original flat vector silhouettes shared by live play, drag, promotion, captures, replay, recent games, and checkmate.",
      "Rebuilt board squares, frames, coordinates, move targets, captures, selection, and check states with solid color and clean rings.",
      "Made Riot the fresh teal-and-ivory default while preserving every existing theme as a palette choice.",
      "Replaced the tilted homepage mock board with a front-on 2D board using the same production pieces.",
    ],
    githubUrl: commitSource("cbe0cac6ddfe5a844483c4fbc804640701b0fe24"),
  },
  {
    version: "0.11.1",
    date: "2026-07-26",
    title: "One game, still moving",
    summary: "The 90-second demo now follows Ron and Omri through one asynchronous match, with the video filling the page instead of sitting below a large headline.",
    changes: [
      "Replaced the feature-list narration with a complete story from warm-up through invitation, reply, return, and replay.",
      "Made the video occupy roughly 90–94% of the viewport width and reduced the page heading to a compact label.",
      "Reordered the real interface captures around the story while removing inactive Magic Rules from the narration.",
      "Versioned the storyboard contract so an outdated Control build cannot publish stale video over the current story.",
    ],
    githubUrl: commitSource("5b53e624f8875efbebeed1f7f6d2122a52848204"),
  },
  {
    version: "0.11.0",
    date: "2026-07-26",
    title: "ChessRiot in 90 seconds",
    summary: "A narrated, captioned walkthrough now shows Solo, themes, replay, and private multiplayer before you start a game.",
    changes: [
      "Added a public 90-second demo page linked directly from the homepage.",
      "Built the walkthrough from current Development interface captures with narration, subtitles, and audio.",
      "Separated video regeneration from application releases by publishing validated media through a versioned R2 manifest.",
      "Added a signed, owner-only, rate-limited regeneration lane for the ChessRiot Control panel.",
    ],
    githubUrl: commitSource("12c7871410470d0d46e3f67216fb944da84d1563"),
  },
  {
    version: "0.10.2",
    date: "2026-07-26",
    title: "Cleaner foundations",
    summary: "Shared gameplay presentation and request logic is now easier to maintain without changing how ChessRiot plays.",
    changes: [
      "Centralized board orientation, piece labels, difficulty labels, outcome text, and live status text.",
      "Centralized new-game request payloads and authenticated client request helpers.",
      "Added focused regression tests while preserving the Magic Rules Coming Soon boundary.",
    ],
    githubUrl: commitSource("45d3910230a5f19a701c2731f5abb767b8c077f2"),
  },
  {
    version: "0.10.1",
    date: "2026-07-26",
    title: "Magic safely paused",
    summary: "Magic Rules remain visible, but new rule entry is paused while the feature develops in isolation.",
    changes: [
      "Replaced new-game Magic rule entry with a clear Coming Soon placeholder.",
      "Removed the runtime LLM compiler, its endpoint, and its token-consuming path from the stable release.",
      "Moved active Magic development to an isolated feature branch and preview lane.",
    ],
    githubUrl: commitSource("31be1f32efc249b91c49d2918be831d023ad2395"),
  },
  {
    version: "0.9.3",
    date: "2026-07-26",
    title: "Solo from the start",
    summary: "New games now open in Solo mode, while preserving White's first move in every game.",
    changes: [
      "Selected Solo by default on the new-game screen and showed the Level 3 Riot Bot control immediately.",
      "Kept Multiplayer one tap away without changing either mode's saved behavior.",
      "Added regression coverage for the default selection and the existing White-first invariant.",
    ],
    githubUrl: commitSource("9e047e799a8011a829d8aa64677ea260bd2235e8"),
  },
  {
    version: "0.9.2",
    date: "2026-07-25",
    title: "First-move history fix",
    summary: "Back now works even while the first Magic move of a game is still being staged.",
    changes: [
      "Kept the Back arrow available at ply zero when a staged Magic position is visible.",
      "Made Back cancel that draft and reveal the authoritative starting position.",
    ],
    githubUrl: commitSource("a4da6bdaf8f5e1ede38d6fbf10fab5eb259faf2a"),
  },
  {
    version: "0.9.1",
    date: "2026-07-25",
    title: "History polish",
    summary: "History now follows the position you can actually see, with stronger mobile and keyboard behavior.",
    changes: [
      "Kept the immediately previous position available while a Solo move is shown optimistically.",
      "Made Back from a staged Magic first leg return to the latest authoritative position without skipping a ply.",
      "Removed historical board squares from keyboard navigation while keeping their position labels available.",
      "Moved history controls outside the live status announcement and enlarged their mobile touch targets.",
      "Restored focus safely after move confirmation, including promotion and committed-move flows.",
      "Clarified that Confirm every move is stored in the current browser.",
    ],
    githubUrl: commitSource("2b7ff89b94887325c4dc673eaa79d3317ccbbf33"),
  },
  {
    version: "0.9.0",
    date: "2026-07-25",
    title: "History at hand",
    summary: "Browse earlier positions directly on the board and optionally confirm every move before sending it.",
    changes: [
      "Added always-visible Back and Forward arrows that step through committed positions without changing the live game.",
      "Kept historical viewing pinned when a new move arrives, with a direct Go Live control and frame-specific check, captures, and last-move highlights.",
      "Added a browser-local Confirm every move setting that is off by default.",
      "Applied one confirmation to every human move path, including tap, drag, promotion, and complete atomic Magic turns.",
      "Blocked stale and duplicate confirmations before they can submit a move.",
    ],
    githubUrl: commitSource("959b7339ccb4369b05f3a700fb33e66a89ca06e4"),
  },
  {
    version: "0.8.2",
    date: "2026-07-25",
    title: "One front door",
    summary: "ChessRiot now has one fixed public homepage and direct guest play with no login gate.",
    changes: [
      "Made the public homepage identical for every visitor, independent of hosting identity and saved game theme.",
      "Moved new-game setup to /app and enabled guest Solo and Multiplayer creation with a display name.",
      "Made private seat links authoritative for guest play while preserving existing account memberships and older games.",
      "Limited themes to active games so public, setup, invitation, changelog, loading, and error pages keep one consistent style.",
      "Removed all user-facing login prompts and kept the retired CAPTCHA path absent.",
    ],
    githubUrl: commitSource("f6511bb3f3307b64c52cdf560e087615a38ab2b2"),
  },
  {
    version: "0.8.1",
    date: "2026-07-25",
    title: "Direct entry",
    summary: "Players now enter ChessRiot immediately, without a separate human-check screen.",
    changes: [
      "Removed the Turnstile screen, verification request, and CAPTCHA-bound application session.",
      "Kept trusted hosting identity, account-bound game membership, request-origin checks, and account rate limits.",
      "Retired the old CAPTCHA endpoint and redirected existing verification entry points safely into the game.",
    ],
    githubUrl: commitSource("0365892af512885ce0608ab41b012176401bad82"),
  },
  {
    version: "0.8.0",
    date: "2026-07-25",
    title: "Knights move twice",
    summary: "Magic knights can now move twice, and game requests work correctly inside the production sandbox.",
    changes: [
      "Made “Knights move twice.” a real deterministic Magic Rule for Solo and Multiplayer games.",
      "Generalized atomic two-leg turns so the same enabled rook or knight may move again, while a checking first leg still ends the turn.",
      "Kept existing v1 Magic Rule documents readable and unchanged while storing knight-enabled games in the compatible v2 schema.",
      "Extended tap, drag, keyboard, replay, move history, labels, and Riot Bot play to two-step knights.",
      "Fixed the production request-origin blocker without relaxing cross-site protection.",
    ],
    githubUrl: commitSource("a1205a473fcf467dab86663e3cc2f481096ef890"),
  },
  {
    version: "0.7.0",
    date: "2026-07-25",
    title: "Magic Rules",
    summary: "Every new Solo or Multiplayer game can optionally carry its own safe, immutable rule changes.",
    changes: [
      "Added an optional Magic Rules box to game creation with a concise natural-language prompt.",
      "Compiled recognized prompts into versioned rules and rejected unsupported text instead of executing arbitrary code or silently ignoring it.",
      "Added atomic two-step rook turns: the same rook may move again before the turn ends, while giving check ends the turn immediately.",
      "Added no-promotion, no-castling, and no-en-passant rules with server, client, replay, and Riot Bot enforcement.",
      "Showed Magic Rules before joining, during play, in replay and move history, and on My Games cards.",
    ],
    githubUrl: commitSource("360caa384478b2f26ba1555d36822b278d2fea17"),
  },
  {
    version: "0.6.0",
    date: "2026-07-25",
    title: "Every game, every turn",
    summary: "A complete My Games history and account-aware alerts make asynchronous play reliable across devices.",
    changes: [
      "Added cursor pagination so My Games can reach the complete account history instead of stopping at 50 games.",
      "Added clear Your turn, Opponent's turn, Waiting, Won, Lost, and Draw states to every game card.",
      "Made open-app opponent-move alerts watch all owned multiplayer games through the account session.",
      "Removed the alert dependency on a legacy private-seat token or the currently open game route.",
      "Added a clear Switch Account action through the trusted ChatGPT sign-out flow.",
    ],
    githubUrl: commitSource("f5c7dbbb78eeb1a0bb783bb0f162148ce5efcbb0"),
  },
  {
    version: "0.5.0",
    date: "2026-07-24",
    title: "Secure accounts and a bigger board",
    summary: "Account access, a human check, a board-first layout, and original illustrated themes make ChessRiot safer and more immersive.",
    changes: [
      "Required a ChessRiot account and server-verified CAPTCHA before any game could be created or played.",
      "Added account-bound game access, per-account rate limits, and bot-turn leases to reduce automated abuse and duplicate AI work.",
      "Made the board fill the available desktop or mobile viewport and collapsed secondary match tools.",
      "Showed the starting position before animating Riot Bot’s White opening when the player starts as Black.",
      "Placed captured Black pieces with White and captured White pieces with Black.",
      "Added seven original illustrated theme backgrounds, including medieval army and moonlit castle styles, plus two new themes.",
    ],
    githubUrl: commitSource("664812fc87b77e39ba6cccee9e6c119ebe662411"),
  },
  {
    version: "0.4.1",
    date: "2026-07-24",
    title: "Viewport clearance",
    summary: "Short desktop and landscape layouts keep the board, replay, and controls usable.",
    changes: [
      "Kept the complete game board above the utility dock across common desktop heights.",
      "Preserved usable game and replay board sizes in short landscape viewports with vertical scrolling.",
      "Added clearance after the final mobile card and compacted replay controls around the board.",
      "Removed a duplicate checkmate announcement and made invalid deadline text neutral.",
    ],
    githubUrl: commitSource("5a0ec848f8dc1c5517d00cf33d54946e25a4d534"),
  },
  {
    version: "0.4.0",
    date: "2026-07-24",
    title: "A more personal async game",
    summary: "Themes, replay, safe reactions, install support, and real move deadlines deepen every match.",
    changes: [
      "Added nine original themes for the app, board, pieces, panels, and background.",
      "Added an accessible visual picker that works from every route and synchronizes across tabs.",
      "Added six rate-limited, preset-only multiplayer reactions, a per-game hide control, and a 15-minute Good Game or Thanks courtesy window.",
      "Added a short theme-aware victory finisher with reduced-motion support.",
      "Added a read-only game replay with step controls and keyboard navigation.",
      "Added one, three, or five-day multiplayer move deadlines, defaulting to three days.",
      "Added installable PWA support, an unseen-release dot, and opt-in open-app opponent-move notifications.",
      "Made the exact release version visible on every route and state.",
    ],
    githubUrl: commitSource("04bf82c2a044dae4d4b709bdadc490fe4ee67c85"),
  },
  {
    version: "0.3.5",
    date: "2026-07-24",
    title: "Instant move polish",
    summary: "Immediate solo moves now keep their sound and complete observability trail.",
    changes: [
      "Restored one accepted move or capture sound for the human ply.",
      "Restored game-completion telemetry when Riot Bot delivers the final move.",
      "Kept race telemetry limited to the move that actually committed.",
    ],
    githubUrl: commitSource("6f80b050bf9747625f4c3d4cfa69f905f4d9970a"),
  },
  {
    version: "0.3.4",
    date: "2026-07-24",
    title: "Instant solo moves",
    summary: "Your piece now moves immediately while Riot Bot thinks in the background.",
    changes: [
      "Added a reversible local preview for every legal solo move before the server response arrives.",
      "Made the human move durable and visible before Riot Bot starts its reply.",
      "Added background bot-turn recovery so refresh or browser closure cannot strand a solo game.",
    ],
    githubUrl: commitSource("c704f43d6ffe79ecb1bab9a64596495995ecc2f6"),
  },
  {
    version: "0.3.3",
    date: "2026-07-24",
    title: "Unmistakable piece colors",
    summary: "White and Black now use the same solid voxel-piece shapes with clearly contrasting colors.",
    changes: [
      "Replaced hollow White glyphs with solid light pieces so the player color cannot look inverted.",
      "Reduced the bright outline on Black pieces so they read as Black at a glance.",
    ],
    githubUrl: commitSource("c0032d3567273af368364a649992847f18eda1ec"),
  },
  {
    version: "0.3.2",
    date: "2026-07-24",
    title: "Laptop viewport polish",
    summary: "The complete board now stays inside a common laptop viewport at normal browser zoom.",
    changes: [
      "Tightened the desktop height cap after real-browser visual QA so the board no longer clips at the bottom.",
    ],
    githubUrl: commitSource("8e6c9a924d128a93dc2a9d93211cca749dbcd1e1"),
  },
  {
    version: "0.3.1",
    date: "2026-07-24",
    title: "A clearer, complete game board",
    summary: "The board now fits shorter screens, makes player colors and check unmistakable, and adds captured pieces and game-ending controls.",
    changes: [
      "Made the full board fit common laptop screens at normal browser zoom and increased important label sizes.",
      "Added explicit White and Black player cards plus captured-piece trays.",
      "Highlighted the checked king and explained exactly when a move fails to answer check.",
      "Added New Game and confirmed End Game or Cancel Game actions.",
      "Renamed computer difficulty to bot level.",
    ],
    githubUrl: commitSource("0063f7058a2c8ce1c599b6d0a81dc56168a65fa7"),
  },
  {
    version: "0.3.0",
    date: "2026-07-24",
    title: "A faster start and clearer releases",
    summary: "A much simpler home screen, visible board motion, in-app feedback, and a public version history.",
    changes: [
      "Simplified the new-game flow around name, mode, difficulty, and one primary action.",
      "Added short move and capture animations with reduced-motion support.",
      "Added a feedback form and an owner-only feedback pool.",
      "Added this changelog to every environment.",
    ],
    githubUrl: commitSource("9d5fa7548f96994768d1986483c982423ca78a85"),
  },
  {
    version: "0.2.2",
    date: "2026-07-24",
    title: "Correct solo turns and observability",
    summary: "Riot Bot can now play either color correctly, chess draw rules are more precise, and operations are visible per environment.",
    changes: [
      "Riot Bot opens automatically when it is White.",
      "Added claimable and automatic FIDE draw handling.",
      "Added privacy-safe health, action, error, and latency telemetry.",
    ],
    githubUrl: commitSource("8e51d1ebece1843ed72659a76879d946a778c4ed"),
  },
  {
    version: "0.2.1",
    date: "2026-07-24",
    title: "Version safety",
    summary: "Changed deployments can no longer silently reuse or decrease the app version.",
    changes: [
      "Added a single SemVer source and release commands.",
      "Added build-time checks for reused or inconsistent versions.",
    ],
    githubUrl: commitSource("8e51d1ebece1843ed72659a76879d946a778c4ed"),
  },
  {
    version: "0.2.0",
    date: "2026-07-24",
    title: "Solo play and drag controls",
    summary: "Play Riot Bot at five difficulty levels, or drag pieces in multiplayer.",
    changes: [
      "Added persistent solo games against Riot Bot.",
      "Added five difficulty levels with Medium as the default.",
      "Added mouse and touch drag-and-drop while preserving tap and keyboard input.",
    ],
    githubUrl: commitSource("8e51d1ebece1843ed72659a76879d946a778c4ed"),
  },
  {
    version: "0.1.2",
    date: "2026-07-24",
    title: "Portable private links",
    summary: "Private player links now work across computers and the game has a block-world visual identity.",
    changes: [
      "Embedded the private seat credential safely in the URL fragment.",
      "Added explicit private-link sharing and cross-device recovery.",
      "Restyled the complete experience with an original voxel-inspired look.",
    ],
    githubUrl: commitSource("8e51d1ebece1843ed72659a76879d946a778c4ed"),
  },
  {
    version: "0.1.1",
    date: "2026-07-24",
    title: "Identity, sound, and resilience",
    summary: "The first polish release added ChessRiot’s visual identity, game sounds, and reliability fixes.",
    changes: [
      "Added move, capture, check, result, and invalid-action sounds.",
      "Added mute controls, clearer loading, and safer local storage.",
      "Improved invitation, status, and promotion interactions.",
    ],
    githubUrl: commitSource("a3239b646de477e520b83b1d8ad0405638b23b89"),
  },
  {
    version: "0.1.0",
    date: "2026-07-23",
    title: "Playable async chess",
    summary: "The first public prototype let two people create, join, resume, and finish a legal asynchronous chess game.",
    changes: [
      "Added one-use invitations and private player seats.",
      "Added complete standard chess rules and immutable move history.",
      "Added persistent two-device play with server-authoritative state.",
    ],
    githubUrl: commitSource("213fc7256da030f52927e1ae7206da21e31ec203"),
  },
];

export const SOURCE_URL = REPOSITORY_URL;
